apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  selector:
    matchLabels:
      type: appli
  template:
    metadata:
      name: httpd-frontend-pod
      labels:
        type: appli
    spec:
      containers:
        - name: httpd
          image: httpd:2.4-alpine
  replicas: 3